[ADDED] Metro deps and extensions
Got this issue, hence downgraded mkdocs material

```
Collecting Jinja2==3.1.6 (from -r requirements.txt (line 3))
  Using cached jinja2-3.1.6-py3-none-any.whl.metadata (2.9 kB)
INFO: pip is still looking at multiple versions of mkdocs-material to determine which version is compatible with other requirements. This could take a while.
ERROR: Cannot install -r requirements.txt (line 8), click==8.2.2 and mkdocs-material==9.6.20 because these package versions have conflicting dependencies.

The conflict is caused by:
    The user requested click==8.2.2
    mkdocs 1.6.1 depends on click>=7.0
    mkdocs-material 9.6.20 depends on click<8.2.2

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip to attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts
```